// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irkxtsitqglwimxfbegi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlya3h0c2l0cWdsd2lteGZiZWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjMxNDgsImV4cCI6MjA1ODI5OTE0OH0.AsYC8FWL9roo4g_Ql2vfi9QI6gTkUfgh56o_TU0BZqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to save chat messages
export const saveChatMessage = async (employeeId: string, message: string, isBot: boolean) => {
  if (!employeeId) return null;
  
  const { data, error } = await supabase
    .from('chat_history')
    .insert({
      employee_id: employeeId,
      message,
      is_bot: isBot
    })
    .select()
    .single();
    
  if (error) {
    console.error('Error saving chat message:', error);
    return null;
  }
  
  return data;
};

// Helper function to save user feedback
export const saveFeedback = async (
  employeeId: string, 
  mood: string, 
  comments: string = '',
  assessmentData?: {
    assessment_outcome?: string;
    assessment_history?: any[];
    assessment_type?: string;
    feedback_source?: string;
  }
) => {
  if (!employeeId) return null;
  
  try {
    // Get current authenticated user
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      console.error('No authenticated user found');
      return null;
    }
    
    // Use the current user's ID instead of passed employeeId if "current_user" is specified
    const actualEmployeeId = employeeId === "current_user" ? user.id : employeeId;
    
    console.log('Using employee ID:', actualEmployeeId);
    
    // First ensure the profile exists
    await ensureUserProfile(actualEmployeeId);
    
    // Create complete feedback object with all fields from types.ts
    const feedbackData = {
      employee_id: actualEmployeeId,
      mood,
      comments,
      date: new Date().toISOString(),
      assessment_outcome: assessmentData?.assessment_outcome || null,
      assessment_data: assessmentData?.assessment_history || null, // Include JSON data directly
      assessment_type: assessmentData?.assessment_type || 'recognition_imbalance',
      feedback_source: assessmentData?.feedback_source || 'employee_dashboard',
      submitted: true
    };
    
    console.log('Submitting complete feedback with assessment data:', feedbackData);
    
    // Insert complete feedback data with all fields
    const { data, error } = await supabase
      .from('feedback')
      .insert(feedbackData)
      .select()
      .single();
    
    if (error) {
      console.error('Error saving feedback:', error);
      return null;
    }
    
    return data;
  } catch (err) {
    console.error('Exception in saveFeedback:', err);
    return null;
  }
};

// Helper function to ensure user profile exists (useful for social logins)
export const ensureUserProfile = async (userId: string, userData?: {
  name?: string;
  email?: string;
  role?: "hr" | "employee";
  role_id?: string;
  department?: string;
}) => {
  if (!userId) return null;
  
  // First, check if profile already exists
  const { data: existingProfile, error: fetchError } = await supabase
    .rpc('get_profile', { profile_id: userId });
    
  if (fetchError) {
    console.error('Error checking for existing profile:', fetchError);
    return null;
  }
  
  // If profile exists, return it
  if (existingProfile && existingProfile.length > 0) {
    return existingProfile[0];
  }
  
  // Get auth user data if needed
  let authUser = null;
  if (!userData || !userData.email) {
    const { data: { user } } = await supabase.auth.getUser();
    authUser = user;
  }
  
  // Create new profile
  const newProfile = {
    id: userId,
    name: userData?.name || authUser?.user_metadata?.full_name || authUser?.email?.split('@')[0] || 'User',
    role: userData?.role || 'employee',
    role_id: userData?.role_id || authUser?.user_metadata?.role_id || null,
    department: userData?.department || 'General'
  };
  
  const { data: createdProfile, error: insertError } = await supabase
    .from('profiles')
    .insert(newProfile)
    .select()
    .single();
    
  if (insertError) {
    console.error('Error creating user profile:', insertError);
    return null;
  }
  
  return createdProfile;
};
